---
title: "temel bileşen ve faktör analizi"
author: "Yade İrem Bilgic"
date: "2025-12-16"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(dev="svg")
```
 
```{r load_data}
aids_verisi <- read.csv("aids_veri.csv", header = TRUE, encoding = "windows-1254")

```

```{r variable_conversion}
cd_variables <- c("cd40", "cd420", "cd80", "cd820")
for (var_name in cd_variables) {aids_verisi[[var_name]] <- as.numeric(as.character(aids_verisi[[var_name]]))}
str(aids_verisi[cd_variables])
```

```{r, warning=FALSE}
library(PerformanceAnalytics)
chart.Correlation(aids_verisi[,20:23], histogram = TRUE, pch=19)

```

```{r}
library(corrplot)
corrplot(cor(aids_verisi[,20:23]))
korelasyon <-cor(aids_verisi[,20:23])
korelasyon
```

```{r}
library(Hmisc)
rcorr(as.matrix(aids_verisi[,20:23]),type="pearson")
```
```{r}
korelasyon <- cor(aids_verisi[, 20:23])
det(korelasyon)
```
```{r}
library(matlib)
invkor<-inv(korelasyon)
colnames(invkor)<-rownames(invkor)<-colnames(korelasyon)
```

#PCA Uygulanabilirliği
```{r}
library(psych)
KMO(aids_verisi[,20:23])
```

```{r}
library(psych)
cortest.bartlett(cor(aids_verisi[,20:23]),nrow(aids_verisi))
```
#Temel Bileşenler Analizi
```{r}

cd_variables <- c("cd40", "cd420", "cd80", "cd820")

all_pca_columns <- c(cd_variables)


pca_data_complete <- na.omit(aids_verisi[, all_pca_columns])
pca_matrix <- pca_data_complete[, cd_variables]
```

```{r}
fit.pca <- prcomp( ~., data=pca_matrix, scale=TRUE)
fit.pca$rotation
```
#Bileşen Sayısına Karar Verme
```{r}
summary(fit.pca)
(fit.pca$sdev)^2
```
#Scree Plot
```{r, warning=FALSE}
library(factoextra)
scree <- fviz_eig(fit.pca)
scree
```

#İlk İki Bileşen
```{r}
fit.pca$rotation[,1:2]
fit.pca$rotation[,2]*fit.pca$sdev[2]
```
#Skorları Yazdırma
```{r}
aids_verisi$comp1 <- fit.pca$x[,1] 
aids_verisi$comp2 <- fit.pca$x[,2]
```

#İndeks Oluşturma
```{r}
aids_verisi$index <- aids_verisi$comp1+aids_verisi$comp2
```

#Sıralama
```{r}
head(aids_verisi[order(aids_verisi$index,decreasing = T),1])
```


```{r, warning=FALSE}
library(factoextra)
fviz_pca_var(fit.pca,col.var="steelblue",
             repel = TRUE
)             
```

#İndeks Oluşturma
```{r}
indeks <- apply(fit.pca$x[,1:2],1,sum)
indeks<-order(indeks,decreasing = F)
head(aids_verisi[indeks,1])

          
```
#Kok Lambda ile Faktör Analizi
```{r}
library(psych)
fa_fit <- principal(aids_verisi[,20:23], nfactors = 2, rotate= "varimax")
print(fa_fit$loadings, digits=3, cutoff=.6, sort=TRUE)

          
```
#Faktörlere Göre İndeks Oluşturma
```{r}
aids_verisi <-cbind(aids_verisi,fa_fit$scores)
head(aids_verisi[order(aids_verisi$RC1,decreasing = T),1])
head(aids_verisi[order(aids_verisi$RC2, decreasing = F),1])
     
```
#Faktör Yükü GRafiği
```{r, warning=FALSE}
factor.plot(fa_fit, labels = rownames(fa_fit$loadings),cex=0.4)
```


          


